CREATE DATABASE IF NOT EXISTS gestion_seguros;
CREATE USER IF NOT EXISTS 'safebryan'@'%' IDENTIFIED BY '081012';
GRANT ALL PRIVILEGES ON gestion_seguros.* TO 'safebryan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;